### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by wuwuhahah** [SevaSk/ecoute#120]
I am able to run the software correctly, but I am getting the following prompt in CMD: "You exceeded your current quota, please check your plan and billing details." Additionally, ChatGPT is not providing any prompts.

like this:
D:\git\ecoute>python main.py --api
C:\Users\达琛奇\AppData\Local\Programs\Python\Python311\Lib\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
READY
You exceeded your current quota, please check your plan and billing details.
You exceeded your current quota, please check your plan and billing details.
You exceeded your current quota, please check your plan and billing details.
You exceeded your current quota, please check your plan and billing details.
You exceeded your current quota, please check your plan and billing details.

**Comment by mlubbad** [comment]
This error message indicates that you have exceeded the maximum monthly spend limit for the API. It means you have utilized all the credits or units assigned to your plan and reached the billing cycle limit. Several reasons can lead to this situation, including:

- Using a high-volume or complex service that consumes many credits or units per request.
- It is working with a large or diverse dataset that requires numerous requests for processing.
- Your organization's usage surpasses the set limit.

To resolve this error, please follow these steps:
- Check your current quota in your account settings [here](https://beta.openai.com/account/billing/limits). You can see how many tokens your requests have consumed [here](https://beta.openai.com/account/usage).

- If using a free plan, consider upgrading to a pay-as-you-go plan offering a higher quota.

- If you need a quota increase, apply for one [here](https://beta.openai.com/forms/quota-increase). We will look over your request and get back to you as soon as possible.

**Comment by wuwuhahah** [comment]
Dear ,

Thank you for taking the time to respond to my inquiry. I appreciate your prompt and helpful reply. I have now found a solution to the issue I was facing and no longer require any further assistance.

Once again, I would like to express my gratitude for your assistance. Please do not hesitate to contact me if you need any further information.

Best regards,

wuwuhahah
________________________________
发件人: Mohammed Lubbad ***@***.***>
发送时间: 2023年7月5日 12:11
收件人: SevaSk/ecoute ***@***.***>
抄送: wuwuhahah ***@***.***>; State change ***@***.***>
主题: Re: [SevaSk/ecoute] help (Issue #120)


This error message indicates that you have exceeded the maximum monthly spend limit for the API. It means you have utilized all the credits or units assigned to your plan and reached the billing cycle limit. Several reasons can lead to this situation, including:

  *   Using a high-volume or complex service that consumes many credits or units per request.
  *   It is working with a large or diverse dataset that requires numerous requests for processing.
  *   Your organization's usage surpasses the set limit.

To resolve this error, please follow these steps:

  *   Check your current quota in your account settings here<https://beta.openai.com/account/billing/limits>. You can see how many tokens your requests have consumed here<https://beta.openai.com/account/usage>.

  *   If using a free plan, consider upgrading to a pay-as-you-go plan offering a higher quota.

  *   If you need a quota increase, apply for one here<https://beta.openai.com/forms/quota-increase>. We will look over your request and get back to you as soon as possible.

―
