### ISSUE TITLE
Potential Cost Incurred by Leaving Terminal Command Open for Extended Periods

### ISSUE THREAD

**Issue by khanhthanhh9** [SevaSk/ecoute#17]
inadvertently left the terminal command open on my PC for a continuous 6-hour duration, resulting in an approximate expenditure of $1.5 due to ongoing prompts, despite having turned off the UI tkinter. Considering the possibility of others encountering the same accidental behavior, I would like to share this issue here.

**Comment by SevaSk** [comment]
Sorry! Just pushed a change https://github.com/SevaSk/ecoute/commit/392235ec296b4cdd593f0260049f616339210dee to fix this.

**Comment by khanhthanhh9** [comment]
Thank you for your fast fix!
