### ISSUE TITLE
Use a different function for the response suggestions?

### ISSUE THREAD

**Issue by MustaphaU** [SevaSk/ecoute#19]
Would it be possible to use a different API or function for the response suggestions? In my experience, I have not not been able to use that functionality due to always exceeding my quota.  Are there any other free or opensource models that can be used in place of OpenAI gpt-3.5-turbo-0301 ?

![image](https://github.com/SevaSk/ecoute/assets/123378149/60be3b25-da32-43c4-afa8-29627ba4ec99)

**Comment by SevaSk** [comment]
While there may be other free or open-source models to choose from, this project utilizes the OpenAI GPT for its superior performance. If you're interested in modifying the code to employ other models, feel free to do so! I believe the only changes in the code would be in the generate_response_from_transcript method.

**Comment by MustaphaU** [comment]
I agree -- OpenAI's GPT is superior to most other similar models. Thanks for the tip, also for putting this together.
