### ISSUE TITLE
Issue with immediate startup crash

### ISSUE THREAD

**Issue by isaacsouthwell** [SevaSk/ecoute#2]
I ran into an issue trying to run the code. Python version 3.11, all requirements were installed via requirements.txt. ![image](https://github.com/SevaSk/ecoute/assets/120406132/f20eb2d4-fb5a-4591-a2f8-eb96a3165a50)

**Comment by SevaSk** [comment]
Hey! I recently added FFMPEG to the prerequisites. This issue might be related to that if you dont have it downloaded.

**Comment by jimmcq** [comment]
I ran into the exact same issue

**Comment by nasraja** [comment]
Same issue here. There is an exception with the win32 createprocess when generating transcript. 

Yet to debug properly.

**Comment by SevaSk** [comment]
The easiest way to set up FFMPEG would be to run these two commands in admin PowerShell:
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```
```
choco install ffmpeg
```

**Comment by jimmcq** [comment]
Yes, that worked for me.
