### ISSUE TITLE
Filenotfounderror

### ISSUE THREAD

**Issue by nithinkrishnac** [SevaSk/ecoute#24]
![IMG-20230527-WA0034.jpg](https://github.com/SevaSk/ecoute/assets/111739864/17e0a871-e9ba-43ec-9a55-ce557f0a6bfb)

**Comment by SevaSk** [comment]
I don't think you have FFMPEG installed run these two commanded listed in the prerequisites of the README

```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

```
choco install ffmpeg-full
```

**Comment by nithinkrishnac** [comment]
> I don't think you have FFMPEG installed run these two commanded listed in the prerequisites of the README
> 
> ```
> Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
> ```
> 
> ```
> choco install ffmpeg-full
> ```

But I already installed chocolatey and executed these codes successfully

**Comment by SevaSk** [comment]
Hmm not sure for the logs it looks like an issue with using whisper. Could you see if you can get a demo whisper script running on your computer?
