### ISSUE TITLE
No response 

### ISSUE THREAD

**Issue by nithinkrishnac** [SevaSk/ecoute#25]
![IMG-20230528-WA0007.jpg](https://github.com/SevaSk/ecoute/assets/111739864/cb5c9657-7441-4904-8caa-612cfd14227e)

**Comment by SevaSk** [comment]
Could you provide the console output as well?

**Comment by nithinkrishnac** [comment]
> Could you provide the console output as well?

![IMG-20230528-WA0026.jpg](https://github.com/SevaSk/ecoute/assets/111739864/c58a9975-e2b4-42f7-b3cf-cc1a6461c779)

**Comment by SevaSk** [comment]
Hey! You need to add credits to your Open AI account to use the GPT API https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please

**Comment by nithinkrishnac** [comment]
> Hey! You need to add credits to your Open AI account to use the GPT API https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please

My api usage limit was expired,i created a new chatgpt account with new email and phone number and it's API worked 🥹
