### ISSUE TITLE
No Response From GPT

### ISSUE THREAD

**Issue by bryanwux** [SevaSk/ecoute#28]
Description: 
After I ran `python main.py`, everything else works fine, but I can not get the response from GPT. 
Anyone can help?

<img width="1268" alt="issue" src="https://github.com/SevaSk/ecoute/assets/17968665/ca13c5bb-31d8-450e-a836-5831856d41bc">

<img width="745" alt="issue2" src="https://github.com/SevaSk/ecoute/assets/17968665/b64b3bf8-0b62-4969-ae24-e7201bf1ff09">

**Comment by SevaSk** [comment]
Looking at the console log. It might have to do with your openai key authentication according to this post
https://stackoverflow.com/questions/76309228/how-can-i-troubleshoot-an-empty-authenticationerror-when-using-the-openai-api-in

Double check if your openai key is correct

**Comment by bryanwux** [comment]
You are right, it works after I update my api key. Thank you!

**Comment by uddinaq** [comment]
i checked if my api key is correct and it is, it is still not working. Do i have to pay for the tokens?
