### ISSUE TITLE
cannot access local variable 'result'

### ISSUE THREAD

**Issue by Zxcoko** [SevaSk/ecoute#33]
Please help it showed this when I run the main.py. I don't know if there is anything I made wrong. Thanks

![image](https://github.com/SevaSk/ecoute/assets/134996123/204e3c76-058e-4c46-af7d-4a492ef2b088)

**Comment by SevaSk** [comment]
Sorry about that I didn't handle the exception case correctly causing the crash. I fixed that now. You can pull latest main. I am still a bit worried why we are seeing 
![image](https://github.com/SevaSk/ecoute/assets/50382291/23168706-eea4-4400-b921-a6e312b33d98)

Might be a windows file permission error? Could you try the new main and see if you still get this issue?

**Comment by Zxcoko** [comment]
Great! I tried the new main and it works perfectly now! Thanks for your help!
