### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by ak2digi** [SevaSk/ecoute#36]
![null_bytes_error](https://github.com/SevaSk/ecoute/assets/61502494/6f67ebb9-5cff-49cc-908d-54e0e49f8a7b)

**Comment by SevaSk** [comment]
I've updated the REAMME so the command is now
```
echo OPENAI_API_KEY="API KEY" > keys.py
```

try deleting the keys.py file and trying this command
