### ISSUE TITLE
File Encoding

### ISSUE THREAD

**Issue by alma765** [SevaSk/ecoute#37]
this `echo 'OPENAI_API_KEY = "API KEY"' > keys.py`
encodse the keys.py in the wrong format and gives error when running.
Make sure the file is saved in utf8 before running. 

Was getting this error otherwise 
Traceback (most recent call last):
  File "C:\Users\New User\Desktop\ecoute\main.py", line 3, in <module>
    from GPTResponder import GPTResponder
  File "C:\Users\New User\Desktop\ecoute\GPTResponder.py", line 2, in <module>
    from keys import OPENAI_API_KEY
ValueError: source code string cannot contain null bytes

**Comment by SevaSk** [comment]
Thanks, updated the README to this command 

```python -c "with open('keys.py', 'w', encoding='utf-8') as f: f.write('OPENAI_API_KEY=\"API KEY\"')"
```
