### ISSUE TITLE
Rewrite in Other Languages to Support More OSs

### ISSUE THREAD

**Issue by momaee** [SevaSk/ecoute#38]
Is anyone here interested in rewriting it in Go or Rust to also support Mac and Linux? Because as I see `PyAudioWPatch` is just for Windows. Also could be an idea to see if the implementation in Go or Rust is faster or not!

**Comment by momaee** [comment]
Cool @enemaliwilliam. appreciate it. I created this [repo](https://github.com/momaee/go-ecoute) and added you to it. What I'm doing is asking chatgpt to help to convert the code to golang and then try to debug it. we can start some threads in that repo if you agree for more details.

**Comment by SevaSk** [comment]
Hi the limitations causing issues with supporting other OS's does not have anything to do with the language it is written in and rewriting the code is out of the scope of this project.
