### ISSUE TITLE
An error occurred while Running Ecoute

### ISSUE THREAD

**Issue by ravichandrachevula04** [SevaSk/ecoute#39]
after executing the command "python main.py" I came across below issue 

![Screenshot 2023-05-30 183200](https://github.com/SevaSk/ecoute/assets/135064505/62c249b5-bde3-4a00-8016-4eaa98ba127f)

**Comment by SevaSk** [comment]
Did you install the requirements?

**Comment by ravichandrachevula04** [comment]
Yes, I did.
1. Installed Python 3.11
2. Created an account in Open AI and took its Open API Key.
3. Installing this on Windows OS
4. Installed FFmpeg

Did I do it right ?

**Comment by SevaSk** [comment]
Do you do this command 
![image](https://github.com/SevaSk/ecoute/assets/50382291/ff41aa67-f2d0-4f16-8e10-976b50d19397)

**Comment by ravichandrachevula04** [comment]
I uninstalled everything from the scratch and I can see below warnings 
 
![Screenshot 2023-05-30 203644](https://github.com/SevaSk/ecoute/assets/135064505/6a8bc94b-ec14-4f3c-bd44-24a6492a8fb8)

and for your above comment, that commend was not working for me so I have used below 
`python -m pip install -r requirement.txt`

**Comment by SevaSk** [comment]
Not really sure, try using the whisper import in a simple script and go from there.

**Comment by ravichandrachevula04** [comment]
I did a small mistake in my installation now I found the cause and I fixed it, but now I'm facing below issue. Can you please look into it ?

![Screenshot 2023-05-30 211046](https://github.com/SevaSk/ecoute/assets/135064505/5a321c83-5a8a-4199-adf6-3d74d4a1aa6a)

**Comment by SevaSk** [comment]
You need to run that command 
```
python -c "with open('keys.py', 'w', encoding='utf-8') as f: f.write('OPENAI_API_KEY=\"API KEY\"')"
```
in the terminal

the file should look like 

OPENAI_API_KEY="API KEY"

**Comment by ravichandrachevula04** [comment]
After completing 3rd installation point

1. I have created a key.py (in notepad++ as UTF-8) saved it in Ecoute folder 
2. The file contain my OPENAI_API_KEY="API KEY"
3. I have executed below command 
`python -c "with open('keys.py', 'w', encoding='utf-8') as f: f.write('OPENAI_API_KEY=\"API KEY\"')"`
4. and I see below issue

![Screenshot 2023-05-30 220036](https://github.com/SevaSk/ecoute/assets/135064505/3731942f-7b76-4373-a7f5-76930f01a4e1)

Am I missing something here ?

**Comment by SevaSk** [comment]
If you have a keys.py file containing  OPENAI_API_KEY="API KEY" with you actual key then run ecoute and it should work
