### ISSUE TITLE
Option to include prompts/documentation

### ISSUE THREAD

**Issue by JhdChk** [SevaSk/ecoute#4]
Hi,

First of all thank you for sharing this very interesting project.

I was wondering if it would be possible to add a prompt feature in order to guide chatgpt answering in a specific tone or with specific information etc. It would be also very interesting to include files upload too (pdf, csv) in order to give it some data and base the answers upon those files.

What do you think about that?

**Comment by SevaSk** [comment]
Thanks! It would certainly be possible. We have the prompt creation in the create_prompt method: https://github.com/SevaSk/ecoute/blob/main/prompts.py. You can modify that method to take addition information as well as the transcript.

**Comment by SevaSk** [comment]
Opened another issue related to improve the response generated https://github.com/SevaSk/ecoute/issues/12.
