### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by Barhoush** [SevaSk/ecoute#47]
I had this error at the beginning when I was a Free Tier User. 
I upgraded my plan into ChatGPT Plus, created a new API KEY and changed it in keys.py but I still get this error directly after Escoute interface pops out:
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
READY
You exceeded your current quota, please check your plan and billing details.
You exceeded your current quota, please check your plan and billing details.
You exceeded your current quota, please check your plan and billing details.

**Comment by shenhuanum1** [comment]
Don't understand
