### ISSUE TITLE
Encoute running successfully, but no results.  Exceeded quota ??

### ISSUE THREAD

**Issue by jakirhussainp7** [SevaSk/ecoute#49]
Hello,
I've installed encoute as referred in the documentation. Installation completed successfully. When I ran the program using the command `python main.py --api` it was executed smoothly. When I tried to play a couple of audio files, I can't see any results in the response section. 
I've only one default system microphone and permissions are also given.  What am I missing here ??

![image](https://github.com/SevaSk/ecoute/assets/52064414/3bb50223-0df0-4e92-b618-647d762fd3e2)

![image](https://github.com/SevaSk/ecoute/assets/52064414/199ea355-389e-44b2-84e2-5666f259f89c)

What does it mean by exceeded quota ??

![image](https://github.com/SevaSk/ecoute/assets/52064414/e8bf1c1c-0217-4050-8b4a-40e3b7f3f612)

**Comment by SevaSk** [comment]
Hi! To use the gpt 3.5 API and whisper API your key must be set up with an account with openai credits.
https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please
