### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by nichoqu** [SevaSk/ecoute#54]
Hi
When I ran the code I got " [WinError 2] The system cannot find the file specified". I downloaded and used files on 5/31/2023; therefore; my main file is new.

E:\test\ecoute>python   main.py
C:\Users\KPP\AppData\Local\Programs\Python\Python39\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
[INFO] Whisper using GPU: True
READY
[WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified

**Comment by SkywingsWang** [comment]
Same problem

**Comment by SevaSk** [comment]
Are you using the lastest main branch? I recently added a commit to try to address this. But I cant reproduce locally 🤷

**Comment by SevaSk** [comment]
Just push a new commit LMK if it works after pulling

**Comment by nichoqu** [comment]
> Just push a new commit LMK if it works after pulling

I do not understand what you mean!!

**Comment by Barnickal** [comment]
> Just push a new commit LMK if it works after pulling

What does this mean? Thanks

**Comment by pramodvasireddy** [comment]
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
[INFO] Whisper using GPU: False
READY
[WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified
[WinError 2] The system cannot find the file specified

same issue, I am using latest code

**Comment by talhaouianas** [comment]
the same problem, can someone solve this problem ?

[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
[INFO] Whisper using GPU: False
READY
[WinError 2] Le fichier spécifié est introuvable
[WinError 2] Le fichier spécifié est introuvable

**Comment by SevaSk** [comment]
I pushed another change to main. Could someone who is facing this issue try again with the latest changes to see if it works? Again hard to debug since I cant reproduce locally.

**Comment by SevaSk** [comment]
Also make sure you have ffmpeg installed

**Comment by SevaSk** [comment]
If you are facing this issue, it is because you do not have FFMPEG installed. Please look at the Prerequisites in the README. 
I added a check in the code if you don't have FFMPEG installed to give a more descriptive error message in the latest version.
