### ISSUE TITLE
The last step shows the problem  ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by Jasonlee6789** [SevaSk/ecoute#55]
Hi there, 
When I reach the last step, it shows the following message, I check the key.py file,no null bytes
Could you please help me to solve this step?Thank you 
PS C:\Windows\system32\Ecoute> python main.py
Traceback (most recent call last):
  File "C:\Windows\system32\Ecoute\main.py", line 3, in <module>
    from GPTResponder import GPTResponder
  File "C:\Windows\system32\Ecoute\GPTResponder.py", line 2, in <module>
    from keys import OPENAI_API_KEY
ValueError: source code string cannot contain null bytes
PS C:\Windows\system32\Ecoute> python main.py --api
Traceback (most recent call last):
  File "C:\Windows\system32\Ecoute\main.py", line 3, in <module>
    from GPTResponder import GPTResponder
  File "C:\Windows\system32\Ecoute\GPTResponder.py", line 2, in <module>
    from keys import OPENAI_API_KEY
ValueError: source code string cannot contain null bytes

**Comment by SevaSk** [comment]
Hmm, Is the file saved with utf-8 encoding? Try remaking the file.

**Comment by Jasonlee6789** [comment]
Thanks for the swift response, @SevaSk 
I am not clearly understand how to do to save the file with utf-8 encoding?
 I have tried to save as to check if there is an option to choose the utf-8 encoding option.
![image](https://github.com/SevaSk/ecoute/assets/50064245/384e365b-64fa-4078-bd04-8587b4f7dfad)

**Comment by Jasonlee6789** [comment]
![image](https://github.com/SevaSk/ecoute/assets/50064245/faa4abd6-1cd4-4762-9faf-37abf366e8f8)
keys.py This file like snap there is no  null bytes in string

**Comment by SevaSk** [comment]
Try running this command in the ecoute directory 
```
python -c "with open('keys.py', 'w', encoding='utf-8') as f: f.write('OPENAI_API_KEY=\"API KEY\"')"
```

with API KEY your actual key.

**Comment by Jasonlee6789** [comment]
![image](https://github.com/SevaSk/ecoute/assets/50064245/2de8a0cc-e485-495a-b30b-e8428d6a2c0a)
Does the snap show is there some problem in my copied keys?

**Comment by Jasonlee6789** [comment]
![image](https://github.com/SevaSk/ecoute/assets/50064245/9a9b8982-6f9d-49af-877b-7f40a29935e1)
Error line 3 shows keys.py have problem @SevaSk

**Comment by Jasonlee6789** [comment]
Thanks I follow your advice and solve the problem.
thank you @SevaSk

**Comment by SevaSk** [comment]
Thanks!

**Comment by aaronhu1987** [comment]
Hi @SevaSk ,

I faced the same problem , but it didn't work with

`python -c "with open('keys.py', 'w', encoding='utf-8') as f: f.write('OPENAI_API_KEY=\"_API KEY_\"')"`
Should I only just replace my key from _API KEY_?

It showed  `SyntaxError: unterminated string literal (detected at line 1)`
May I know how to fix it?
