### ISSUE TITLE
Add multilingual interviews and responses in another language

### ISSUE THREAD

**Issue by camilolb** [SevaSk/ecoute#58]
Hello, it will be possible that soon we will have the option of doing interviews in another language.

My first language is Spanish but I want to access the American market and I just need you to transcribe and give me answers in both English and Spanish

**Comment by michael7908** [comment]
My first language is not English either but I think maybe you can think about editing the Py file to add other languages. Just thinking loudly.

**Comment by dharmsi** [comment]
Is Tamil?
