### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by dav1dwar10ck** [SevaSk/ecoute#6]
[Running] python -u "d:\ecoute\main.py"
C:\Users\dav1d\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: [1mThe 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.[0m
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "d:\ecoute\main.py", line 3, in <module>
    from GPTResponder import GPTResponder
  File "d:\ecoute\GPTResponder.py", line 2, in <module>
    from keys import OPENAI_API_KEY
ValueError: source code string cannot contain null bytes

[Done] exited with code=1 in 2.24 seconds

**Comment by CatsMeow492** [comment]
This happens due to the encoding of the file using the echo method to produce the keys file uses.

Just open up your favorite IDE or text editor and copy paste `OPENAI_API_KEY = "YOUR_KEY"` and save the old fashion way
