### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Altamash330** [SevaSk/ecoute#65]
hi, can anyone help me installing this! please help me

**Comment by SevaSk** [comment]
Please read the README for instructions

**Comment by ashesstash** [comment]
I read the README instructions but I keep having the following issue

git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ git clone https://github.com/SevaSk/ecoute
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
