### ISSUE TITLE
Unable to access the file.

### ISSUE THREAD

**Issue by KyrieQiu** [SevaSk/ecoute#68]
I have installed all packages needed but the function can not worked out:
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
[INFO] Whisper using GPU: False
READY
[WinError 2] The system can not find the file specified
[WinError 2] The system can not find the file specified
[WinError 2] The system can not find the file specified

It showed up a GUI but not worked out.   I really appreciate your good project : ）

**Comment by KyrieQiu** [comment]
I installed FFmpeg again. It works right now. But i do think this project can be improved and extended to multi-language version and beneficial to more people.

**Comment by SevaSk** [comment]
Try 
'''
python main.py --api 
'''

This works faster and multilingual
