### ISSUE TITLE
Ecoute is transcribing the speaker and my speech on the left hand screen in the GUI, but no output on the right hand screen.

### ISSUE THREAD

**Issue by ragar01** [SevaSk/ecoute#69]
Ecoute is transcribing Speaker and my speech into words on the GUI, but no output on the right hand column.

 The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
[INFO] Whisper using GPU: False
READY

**Comment by SevaSk** [comment]
If there was an issue with the GPT reponse it should show that in console.

Could you also try using 

```
python main.py --api
```

**Comment by ragar01** [comment]
PS C:\WINDOWS\system32\ecoute> python main.py --api
`C:\Users\Timeout-2\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\timing.py:58:` NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
READY
<empty message>
<empty message>
<empty message>

**Comment by ragar01** [comment]
Does not transcribe anything and no output from GPT is seen.

**Comment by Nimishbansal-16** [comment]
in my case its also showing no output, because in the terminal its saying that I have exceeded my current quota. Can you guys explain how many api calls get made on using this, at what interval call is made, and which plan do i need to use, because from starting its showing quota exceeded however i havent used it once

**Comment by SevaSk** [comment]
Hey! To use ChatGPT with your open ai key you need to set up billing on ur open ai account https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please
