### ISSUE TITLE
ModuleNotFoundError: No module named 'whisper'

### ISSUE THREAD

**Issue by peratik** [SevaSk/ecoute#70]
Hello

`python main.py` command returns `ModuleNotFoundError: No module named 'whisper'` error, please advise.

System:
- Windows 11 Home, 22H2, 22621.1778, 64-bit operating system, x64-based processor
- Python 3.10.11 
- `pip install -r requirements.txt`: installed successfully
- `ffmpeg` installed
- `keys.py` file created with `OPENAI_API_KEY="sk-***"` value

```
(env) C:\Users\Saeid\Desktop\ecoute>ffmpeg
ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
```

Error:
```
(env) C:\Users\Saeid\Desktop\ecoute>python main.py         
Traceback (most recent call last):
  File "C:\Users\Saeid\Desktop\ecoute\main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "C:\Users\Saeid\Desktop\ecoute\AudioTranscriber.py", line 1, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'
```

Thank you

**Comment by SevaSk** [comment]
Check if your pip is linked to your correct python version. Closing this since it issue with pip and python not this project.
