### ISSUE TITLE
How to stop listening to me

### ISSUE THREAD

**Issue by pramodvasireddy** [SevaSk/ecoute#71]
The application works great, and I want to know how to stop listening to me. It is listening to my voice and searching in chatGPT. I want to stop that.

**Comment by SevaSk** [comment]
Hey its designed to listen to both the mic and the speaker. If you want to it listen to just the speaker you have to modify the source code.

Deleting this line in main.py 
```
user_audio_recorder = AudioRecorder.DefaultMicRecorder()
```

and passing None here for user_audio_recorder.source

```
transcriber = AudioTranscriber(user_audio_recorder.source, speaker_audio_recorder.source, model)
```
Should be enough

**Comment by pramodvasireddy** [comment]
D:\ecoute>python main.py --api
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
Traceback (most recent call last):
  File "D:\ecoute\main.py", line 125, in <module>
    main()
  File "D:\ecoute\main.py", line 87, in main
    transcriber = AudioTranscriber(user_audio_recorder.source, None, model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ecoute\AudioTranscriber.py", line 33, in __init__
    "sample_rate": speaker_source.SAMPLE_RATE,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'SAMPLE_RATE'

I did as you said, It did not work
