### ISSUE TITLE
I can see the questions but no answer

### ISSUE THREAD

**Issue by harberdy** [SevaSk/ecoute#79]
Hi, I ran the code and it was successful. My speaker is working fine and i can see the questions on the left side but no answer is coming out on the right side? What can i do? I can freeze and un freeze but nothing in the box. I keep seeing in the command promt that had exceeded my quota.
![Screenshot 2023](https://github.com/SevaSk/ecoute/assets/112672756/a21b465a-0283-4da2-9ebc-91a26065439e)

**Comment by roninazure** [comment]
I am having similar issues but it seems the microphone isn't able to send any input into the app. Also get the "You exceeded your current quota, please check your plan and billing details." 

Could this be a VM issue with Azure. I have enabled audio redirection via RDP.

**Comment by harberdy** [comment]
am getting this too."You exceeded your current quota, please check your plan and billing details." are we suppose to pay for it?

**Comment by roninazure** [comment]
> am getting this too."You exceeded your current quota, please check your plan and billing details." are we suppose to pay for it?

I have almost 200$ in credits so I should be good. Is tour mike and speakers working?

**Comment by harberdy** [comment]
I dont think i paid. How did you pay? speakers are working.

**Comment by roninazure** [comment]
> I dont think i paid. How did you pay? speakers are working.

I didn't pay. I have $200 credit with MS Azure.

**Comment by harberdy** [comment]
ok.How did you check?

**Comment by roninazure** [comment]
> ok.How did you check?

On the Azure portal. But this is my VM. It could be a separate thing

**Comment by harberdy** [comment]
ok

**Comment by SevaSk** [comment]
Your openAI key must have access to the openAI API, which means you need to set up a paid openAI account.
https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please
