### ISSUE TITLE
No response when speaking through mic

### ISSUE THREAD

**Issue by Zulks01** [SevaSk/ecoute#81]
Hi, 

Im getting no response when running the app. it does open up the gui but when talking through it nothing is being transcribed

![image](https://github.com/SevaSk/ecoute/assets/135742187/520764a6-a87d-4cc3-b0fb-2bb76a448b1b)

also getting the below in CMD, what does this mean?
"You have exceeded your current quota, please check your plan and billing details"

![image](https://github.com/SevaSk/ecoute/assets/135742187/6ae3cce6-2f5b-4f42-860c-3a7b809d3e78)

**Comment by MrunalPatil14** [comment]
I am getting the same

**Comment by Adarsha-gg** [comment]
You can solve this by using ecoute normally instead of --api. Using --api costs some "points?" from the API key. 
Running it as "python main.py" should do the trick

**Comment by SevaSk** [comment]
Your openAI key must have access to the openAI API, which means you need to set up a paid openAI account.
https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please
