### ISSUE TITLE
can run the main.py but it did not work.

### ISSUE THREAD

**Issue by YangQiuEric** [SevaSk/ecoute#85]
PS C:\Windows\system32>  cd "\\Mac\Home\Documents\chatgpt\ecoute"                                                       PS Microsoft.PowerShell.Core\FileSystem::\\Mac\Home\Documents\chatgpt\ecoute> python main.py
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker..
---
then it is stuck. I tried played some music but still stuck.

**Comment by MrunalPatil14** [comment]
play some video from youtube
