### ISSUE TITLE
how configure to listen in Russian language?

### ISSUE THREAD

**Issue by cool102** [SevaSk/ecoute#9]
Hi, very cool! Its working! So cool!
How configure to listen in Russian language?

**Comment by SevaSk** [comment]
Thanks! Out of the box, one of the limitations is that it's only designed for English. To modify the code so it works with Russian, you would have to update the AudioTranscriber class with the appropriate non-English Whisper model. Here is the Whisper documentation for you to follow: https://github.com/openai/whisper/blob/main/README.md.

**Comment by SevaSk** [comment]
I created an issue https://github.com/SevaSk/ecoute/issues/11 for added multi language support.

**Comment by cool102** [comment]
When are you planning to finalize the multilingual feature?
