### ISSUE TITLE
Exceeded current quota

### ISSUE THREAD

**Issue by akhilgadi** [SevaSk/ecoute#90]
Team,

I have successfully installed and ran the file as well, however its showing me this error - 

![image](https://github.com/SevaSk/ecoute/assets/18099076/5876e208-f0e4-4c89-86aa-6f32cc607153)

Upon checking this article - 

![image](https://github.com/SevaSk/ecoute/assets/18099076/fb9984df-f496-48e4-8753-8957cc03bbea)

To increase my quota, it advised me to "https://beta.openai.com/forms/quota-increase" and directed me to the this form - 

![image](https://github.com/SevaSk/ecoute/assets/18099076/a82da6d9-3a07-4aaa-bce4-1d0b1ab1d4c7)

Could anyone advise me how much I have to load in order to use the ecoute application properly ?

**Comment by SevaSk** [comment]
Ecoute will take about 1 dollar every 8 hours running . Added the smallest about you want,
