### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by Vodofreak** [SevaSk/ecoute#93]
For you kind Assistant please, i got this error "You exceeded your current quota, please check your plan and billing details." . I got API key from a paid openAI . the tab is open it can get into the transcribe but no answer. thanks

**Comment by SevaSk** [comment]
Might need to remake your API key, not sure. Closing this as its an issue with openai API and your key and there is nothing I can do for you to avoid this message.
