### ISSUE TITLE
Not recognizing voice from speaker output

### ISSUE THREAD

**Issue by Abhi11012** [SevaSk/ecoute#98]
In the prompt, I can see my voice coming up but not coming up voice coming out from the system to output any ideas.

<img width="264" alt="image" src="https://github.com/SevaSk/ecoute/assets/80854365/afb971bb-525c-44d2-b487-38cd11c79c64">

**Comment by Farhan293813** [comment]
How did you end up resolving this issue? I have been trying to fix my audio settings and still nothing

**Comment by Abhi11012** [comment]
it started working after some time not sure what was the problem exactly.
